### PR TITLE
[ch898] google-drive: adding support for downloading

### PR DESCRIPTION
**Pull request by damjanovl**

### CODE REVIEW

**Comment by blakeburch** [comment]
4) Following up on issue no1 - I'm also having issues with this when specifying the exact file name. I did this immediately after getting a message about uploading the file successfully.

```
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?q=name+contains+%2710mb_file.csv%27+and+%27None%27+in+parents&fields=files%28id%2C+name%29&alt=json returned "File not found: .">
(gdrive-upload-test) blake@Blakes-MacBook-Pro-2 Blueprint Tests %
```

**Comment by damjanovl** [comment]
> 1. Following up on issue no1 - I'm also having issues with this when specifying the exact file name. I did this immediately after getting a message about uploading the file successfully.
> 
> ```
> googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?q=name+contains+%2710mb_file.csv%27+and+%27None%27+in+parents&fields=files%28id%2C+name%29&alt=json returned "File not found: .">
> (gdrive-upload-test) blake@Blakes-MacBook-Pro-2 Blueprint Tests %
> ```

I haven't been able to reproduce this. Downloading an exact match I get:

```
ldamjanovic@ldamjanovic-ThinkPad-E480:~/shipyard/starter-blueprints/cloud_storage/google_drive$ ../../venv/bin/python download_file.py --source-folder-name TEST_FOLDER/sub_folder --source-file-name new_cloud_test_file_27.txt --source-file-name-match-type exact_match --service-account ./credentials.json 
Using specified json credentials file
NEW_cloud_test_file_27.txt successfully downloaded to /home/ldamjanovic/shipyard/starter-blueprints/cloud_storage/google_drive/new_cloud_test_file_27.txt
```

**Comment by blakeburch** [comment]
Alright - these are the issues still found after our troubleshooting session.
5. The file content isn't actually downloading. Instead it's downloading the json of the file information.
```
{
 "kind": "drive#file",
 "id": "IDHERE",
 "name": "10mb_file.csv",
 "mimeType": "text/csv"
}

```
6. Test 4-7 in `downloads.sh` are failing with the following message. These tests are all trying to download from a multi-sub directory. I also tested it with a single directory with the same results.
```
Traceback (most recent call last):
  File "download_file.py", line 287, in <module>
    main()
  File "download_file.py", line 273, in main
    source_file_name=source_file_name)
  File "download_file.py", line 216, in get_file_blob
    return files.get('files', [])[0]
IndexError: list index out of range
```
I thought we fixed this on the call, but it appears that the fixes for pulling files from the root directory caused issues here.
7. When you use regex match and a source folder, it appears to be looking at the wrong level.

`one/two/three` returns all file matches from folder one, two AND three. It should be ONLY three.
`one/two` returns all file matches from folder one AND two. It should be two AND three.
`one` returns only files matches from one. It should be from one, two AND three.
8. When you use regex match and no source folder, it appears to only choose files from the most recently shared folder, rather than all folders.

I found this because searching for `test.*` returned all of the files from your folder (which you just shared with me) instead of mine. It should return files from both.
9. When a file doesn't exist on Google Drive, you get the following error:
```
Traceback (most recent call last):
  File "download_file.py", line 287, in <module>
    main()
  File "download_file.py", line 273, in main
    source_file_name=source_file_name)
  File "download_file.py", line 216, in get_file_blob
    return files.get('files', [])[0]
IndexError: list index out of range
```
We should make this specifically call out "File could not be found on Google Drive."
10. We're still unable to download files from folders stored on a Shared Drive.

**Comment by blakeburch** [comment]
3) Issue no3 still exists.
>When you specify a Google doc/sheet/slide, it returns the following error but still creates a blank file with the matching name
    googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/FILEID?alt=media returned "Only files with binary content can be downloaded. Use Export with Google Docs files.">

>We don't need to support exporting these files. However, we should make sure that we're not creating blank local files, make sure the error message is a bit more specific, AND that we're not stopping a bulk download process (using regex_match) because of these files.

11) When you use `regex_match`, if a Google Drive directory is found in the match, it will return the same error listed in issue no3.

12) Tests 11-13 returned with
```
Traceback (most recent call last):
  File "download_file.py", line 371, in <module>
    main()
  File "download_file.py", line 336, in main
    prefix=source_folder_name)
  File "download_file.py", line 203, in find_google_drive_file_names
    parent_folder_ids = get_all_folder_ids(service, drive_id=drive)
  File "download_file.py", line 182, in get_all_folder_ids
    fields="files(id, name)").execute()
  File "/Users/blake/.virtualenvs/google-drive/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/blake/.virtualenvs/google-drive/lib/python3.7/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?q=mimeType+%3D+%27application%2Fvnd.google-apps.folder%27&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=drive&driveId=Data+Services&fields=files%28id%2C+name%29&alt=json returned "Shared drive not found: Data Services">

13) Test 14 returned with
```
Traceback (most recent call last):
  File "download_file.py", line 371, in <module>
    main()
  File "download_file.py", line 336, in main
    prefix=source_folder_name)
  File "download_file.py", line 200, in find_google_drive_file_names
    parent_id=parent_folder_id, drive_id=drive)
  File "download_file.py", line 182, in get_all_folder_ids
    fields="files(id, name)").execute()
  File "/Users/blake/.virtualenvs/google-drive/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/blake/.virtualenvs/google-drive/lib/python3.7/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/drive/v3/files?q=mimeType+%3D+%27application%2Fvnd.google-apps.folder%27+and+%27%5B%asdfasdfasdf%27%2C+%adsfasdfasdfasdf%27%5D%27+in+parents&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=drive&driveId=Data+Services&fields=files%28id%2C+name%29&alt=json returned "Invalid Value">
```

**Pull request merged**
