### PR TITLE
[ch899] google drive upload file

### PR DESCRIPTION
**Pull request by damjanovl**

### CODE REVIEW

**Comment by blakeburch** [comment]
1. When a destination folder is being specified via `--destination-folder-name` and it doesn't already exist, it doesn't get created. I was specifically testing this in a directory that already existed in Google Drive (where the service account email had access to it), but the sub-directories didn't yet exist.

See upload test 8 and 9.
2.  When using regex_match, if the text used also matches a folder, the process will error with a `IsADirectoryError: [Errno 21] Is a directory:`

This problem may have existed previously, but was just now caught through more exhaustive testing. Please let us now if this requires some rewrites on the other scripts.
3. `google-api-python-client` needs to be added to the requirements. Otherwise, it returns with `No module named 'googleapiclient'`

**Comment by damjanovl** [comment]
> 1. When a destination folder is being specified via `--destination-folder-name` and it doesn't already exist, it doesn't get created. I was specifically testing this in a directory that already existed in Google Drive (where the service account email had access to it), but the sub-directories didn't yet exist.
> 
> See upload test 8 and 9.
> 2. On the other hand, if all of the subdirectories exist and a `destination-folder-name` is specified, the file gets stored in the first listed directory. So `folder/folder2/` would result in the file getting stored under `folder'.
> 
> 1. When using regex_match, if the text used also matches a folder, the process will error with a `IsADirectoryError: [Errno 21] Is a directory:`
> 
> This problem may have existed previously, but was just now caught through more exhaustive testing. Please let us now if this requires some rewrites on the other scripts.
> 
> 1. `google-api-python-client` needs to be added to the requirements. Otherwise, it returns with `No module named 'googleapiclient'`
> 2. I'm still seeing the less specific error message of `AttributeError: 'MediaFileUpload' object has no attribute '_fd'` when you provide a file to be uploaded that does not exist.
> 3. I confirmed that I'm unable to upload a file to a folder that exists within a shared drive that I have access to. Let me know if you need me to share an example with you.

I've fixed all of these issues in the most recent push.

@blakeburch In regards to #6, I am not able to recreate this issue. I've shared a folder in my personal drive to test with and shared it with my IAM account. I was able to upload to that shared drive with the IAM account using the upload script and confirmed that they existed by opening the files from my personal drive on chrome.

**Comment by blakeburch** [comment]
>4/10 The error for "file name could not be found" isn't specific enough. Instead, the user sees:
AttributeError: 'MediaFileUpload' object has no attribute '_fd'
This issue is still occurring. We want to catch this error with a specific printed message that says "The file name of {file_name} could not be found."

`python3 upload_file.py --source-file-name '10mb_file.csv' --source-file-name-match-type 'exact_match' --service-account "creds.json"` where `10mb_file.csv` doesn't exist.

11 still exists, but I know you're working on it. 😄

**Comment by blakeburch** [comment]
10) Error no10 still exists.
>I'm still seeing the less specific error message of AttributeError: 'MediaFileUpload' object has no attribute '_fd' when you provide a file to be uploaded that does not exist.

12) While issue no8 is no longer a problem, if `regex_match` is used and a directory matches, the script just hangs. It appears like it's pulling data from multiple levels above it. It should only pull files from the current directory and deeper. Try out test 11.1

13) While I verified that the behavior of replacing a file that already existed in a normal Google Drive works correctly, the file gets recreated instead of replaced when you specify a Shared Drive.

14) When you specify a shared drive, and don't include a `source_folder_name` the file doesn't actually get made.

**Pull request merged**
